# Generated by Django 5.2.2 on 2025-07-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_email_verify"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Електронна пошта"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_verify",
            field=models.BooleanField(
                default=False, verbose_name="Підтвердження електронної пошти"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="Номер телефону"),
        ),
    ]
