# Generated by Django 5.2.2 on 2025-07-23 09:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consumables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Назва")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Ціна"
                    ),
                ),
                (
                    "calculation_unit",
                    models.CharField(
                        choices=[
                            ("шт", "Штука"),
                            ("комп", "Комплект"),
                            ("пара", "Пара"),
                            ("упак", "Упаковка"),
                            ("г", "Грам"),
                            ("кг", "Кілограм"),
                            ("т", "Тонна"),
                            ("мм", "Міліметр"),
                            ("см", "Сантиметр"),
                            ("м", "Метр"),
                            ("км", "Кілометр"),
                            ("мл", "Мілілітр"),
                            ("л", "Літр"),
                            ("см³", "Кубічний сантиметр"),
                            ("м³", "Кубічний метр"),
                            ("мм²", "Квадратний міліметр"),
                            ("см²", "Квадратний сантиметр"),
                            ("м²", "Квадратний метр"),
                        ],
                        max_length=50,
                        verbose_name="Одиниця розрахунку",
                    ),
                ),
                (
                    "quantity_units",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Кількість одиниць"
                    ),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Доступний"),
                ),
            ],
            options={
                "verbose_name": "Розхідний матеріал",
                "verbose_name_plural": "Розхідні матеріали",
            },
        ),
        migrations.CreateModel(
            name="Detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thickness",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Товщина (мм)"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Кількість"),
                ),
                (
                    "material_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Вартість матеріалу",
                    ),
                ),
                (
                    "cutting_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Вартість різання"
                    ),
                ),
                (
                    "bending_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Вартість згинання",
                    ),
                ),
                (
                    "drawing_snapshot",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Зліпок креслення"
                    ),
                ),
            ],
            options={
                "verbose_name": "Деталь",
                "verbose_name_plural": "Деталі",
            },
        ),
        migrations.CreateModel(
            name="Drawing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Назва")),
                (
                    "file_path",
                    models.FileField(
                        upload_to="drawings/%Y/%m/%d", verbose_name="Файл креслення"
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        verbose_name="Оригінальна назва файлу",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, editable=False, verbose_name="Розмір файлу (байт)"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата завантаження"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Опис"),
                ),
                (
                    "layers",
                    models.JSONField(
                        blank=True, default=list, null=True, verbose_name="Шари"
                    ),
                ),
                (
                    "process_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Налаштування процесів",
                    ),
                ),
                (
                    "configured",
                    models.BooleanField(default=False, verbose_name="Налаштовано"),
                ),
            ],
            options={
                "verbose_name": "Креслення",
                "verbose_name_plural": "Креслення",
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Назва матеріалу"
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("metal", "Метал"),
                            ("plastic", "Пластик"),
                            ("composites", "Композити"),
                        ],
                        default="metal",
                        max_length=20,
                        verbose_name="Тип матеріалу",
                    ),
                ),
                (
                    "density",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Густина (кг/м³)"
                    ),
                ),
                (
                    "price_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Ціна за кг",
                    ),
                ),
                (
                    "properties",
                    models.TextField(blank=True, null=True, verbose_name="Властивості"),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Доступний"),
                ),
            ],
            options={
                "verbose_name": "Матеріал",
                "verbose_name_plural": "Матеріали",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        default=core.models.generate_order_number,
                        max_length=50,
                        unique=True,
                        verbose_name="Номер замовлення",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Чернетка"),
                            ("pending", "Очікує обробки"),
                            ("processing", "Обробляється"),
                            ("completed", "Завершено"),
                            ("cancelled", "Скасовано"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Загальна вартість",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата оновлення"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Примітки"),
                ),
            ],
            options={
                "verbose_name": "Замовлення",
                "verbose_name_plural": "Замовлення",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Назва"),
                ),
                (
                    "base_cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Базова вартість за одиницю",
                    ),
                ),
                (
                    "cost_unit",
                    models.CharField(
                        max_length=50, verbose_name="Одиниця виміру вартості"
                    ),
                ),
                (
                    "unit_name",
                    models.CharField(max_length=255, verbose_name="Назва одиниці"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Опис"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активний"),
                ),
            ],
            options={
                "verbose_name": "Тип обробки",
                "verbose_name_plural": "Типи обробки",
            },
        ),
    ]
