# Generated by Django 5.2.2 on 2025-06-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drawing",
            name="slug",
        ),
    ]
