# Generated by Django 5.2.2 on 2025-07-02 09:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_drawing_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawing",
            name="angles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="drawing",
            name="length_of_cuts",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
