# Generated by Django 5.2.2 on 2025-07-03 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_drawing_angles_drawing_length_of_cuts"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "base_cost_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("cost_unit", models.CharField(max_length=50)),
                ("unit_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Тип обробки",
                "verbose_name_plural": "Типи обробки",
            },
        ),
        migrations.RemoveField(
            model_name="detail",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="detail",
            name="length",
        ),
        migrations.RemoveField(
            model_name="detail",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="detail",
            name="width",
        ),
        migrations.AddField(
            model_name="drawing",
            name="configured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="drawing",
            name="layers",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="angles",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="file_size",
            field=models.PositiveIntegerField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="original_filename",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.CreateModel(
            name="Consumables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("calculation_unit", models.CharField(max_length=50)),
                ("quantity_units", models.PositiveIntegerField(default=0)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available", models.BooleanField(default=True)),
                (
                    "processing_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processes",
                        to="core.processingtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Розхідні матеріали",
                "verbose_name_plural": "Розхідний матеріал",
            },
        ),
        migrations.AddField(
            model_name="drawing",
            name="processing_types",
            field=models.ManyToManyField(
                related_name="drawings", to="core.processingtype"
            ),
        ),
    ]
