# Generated by Django 5.2.2 on 2025-07-03 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_processingtype_remove_detail_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drawing",
            name="angles",
        ),
    ]
