# Generated by Django 5.2.2 on 2025-07-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_drawing_angles"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawing",
            name="angles",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
