# Generated by Django 5.2.2 on 2025-07-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_drawing_angles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumables",
            name="calculation_unit",
            field=models.CharField(
                choices=[
                    ("шт", "Штука"),
                    ("комп", "Комплект"),
                    ("пара", "Пара"),
                    ("упак", "Упаковка"),
                    ("г", "Грам"),
                    ("кг", "Кілограм"),
                    ("т", "Тонна"),
                    ("мм", "Міліметр"),
                    ("см", "Сантиметр"),
                    ("м", "Метр"),
                    ("км", "Кілометр"),
                    ("мл", "Мілілітр"),
                    ("л", "Літр"),
                    ("см³", "Кубічний сантиметр"),
                    ("м³", "Кубічний метр"),
                    ("мм²", "Квадратний міліметр"),
                    ("см²", "Квадратний сантиметр"),
                    ("м²", "Квадратний метр"),
                ],
                max_length=50,
            ),
        ),
    ]
