# Generated by Django 5.2.2 on 2025-07-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_consumables_calculation_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawing",
            name="length_of_cuts",
            field=models.FloatField(default=0),
        ),
    ]
