# Generated by Django 5.2.2 on 2025-07-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_drawing_length_of_cuts"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawing",
            name="bending_layers",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="drawing",
            name="cutting_layers",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
