# Generated by Django 5.2.2 on 2025-07-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_drawing_bending_layers_drawing_cutting_layers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="price_unit_area",
        ),
        migrations.AddField(
            model_name="material",
            name="density",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="material",
            name="properties",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
