# Generated by Django 5.2.2 on 2025-07-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_material_price_unit_area_material_density_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="density",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="material",
            name="properties",
            field=models.TextField(blank=True, null=True),
        ),
    ]
