# Generated by Django 5.2.2 on 2025-07-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_material_density_alter_material_properties"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="price_per_kg",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
