# Generated by Django 5.2.2 on 2025-07-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_material_price_per_kg"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detail",
            old_name="calculated_cost",
            new_name="bending_cost",
        ),
        migrations.AddField(
            model_name="detail",
            name="cutting_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="detail",
            name="material_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
