# Generated by Django 5.2.2 on 2025-07-20 15:32

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_rename_calculated_cost_detail_bending_cost_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consumables",
            options={
                "verbose_name": "Розхідний матеріал",
                "verbose_name_plural": "Розхідні матеріали",
            },
        ),
        migrations.RemoveField(
            model_name="consumables",
            name="unit_price",
        ),
        migrations.AddField(
            model_name="detail",
            name="drawing_snapshot",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Зліпок креслення"
            ),
        ),
        migrations.AlterField(
            model_name="consumables",
            name="available",
            field=models.BooleanField(default=True, verbose_name="Доступний"),
        ),
        migrations.AlterField(
            model_name="consumables",
            name="calculation_unit",
            field=models.CharField(
                choices=[
                    ("шт", "Штука"),
                    ("комп", "Комплект"),
                    ("пара", "Пара"),
                    ("упак", "Упаковка"),
                    ("г", "Грам"),
                    ("кг", "Кілограм"),
                    ("т", "Тонна"),
                    ("мм", "Міліметр"),
                    ("см", "Сантиметр"),
                    ("м", "Метр"),
                    ("км", "Кілометр"),
                    ("мл", "Мілілітр"),
                    ("л", "Літр"),
                    ("см³", "Кубічний сантиметр"),
                    ("м³", "Кубічний метр"),
                    ("мм²", "Квадратний міліметр"),
                    ("см²", "Квадратний сантиметр"),
                    ("м²", "Квадратний метр"),
                ],
                max_length=50,
                verbose_name="Одиниця розрахунку",
            ),
        ),
        migrations.AlterField(
            model_name="consumables",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="consumables",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Ціна"
            ),
        ),
        migrations.AlterField(
            model_name="consumables",
            name="processing_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="processes",
                to="core.processingtype",
                verbose_name="Тип обробки",
            ),
        ),
        migrations.AlterField(
            model_name="consumables",
            name="quantity_units",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Кількість одиниць"
            ),
        ),
        migrations.AlterField(
            model_name="detail",
            name="bending_cost",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Вартість згинання"
            ),
        ),
        migrations.AlterField(
            model_name="detail",
            name="cutting_cost",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Вартість різання"
            ),
        ),
        migrations.AlterField(
            model_name="detail",
            name="drawing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="details",
                to="core.drawing",
                verbose_name="Креслення",
            ),
        ),
        migrations.AlterField(
            model_name="detail",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="core.material",
                verbose_name="Матеріал",
            ),
        ),
        migrations.AlterField(
            model_name="detail",
            name="material_cost",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Вартість матеріалу"
            ),
        ),
        migrations.AlterField(
            model_name="detail",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="core.order",
                verbose_name="Замовлення",
            ),
        ),
        migrations.AlterField(
            model_name="detail",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Кількість"),
        ),
        migrations.AlterField(
            model_name="detail",
            name="thickness",
            field=models.DecimalField(
                decimal_places=3, max_digits=10, verbose_name="Товщина (мм)"
            ),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="angles",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Кути"
            ),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="bending_layers",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Шари згинання"
            ),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="configured",
            field=models.BooleanField(default=False, verbose_name="Налаштовано"),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="cutting_layers",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Шари різання"
            ),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="file_path",
            field=models.FileField(
                upload_to="drawings/%Y/%m/%d", verbose_name="Файл креслення"
            ),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="file_size",
            field=models.PositiveIntegerField(
                blank=True, editable=False, verbose_name="Розмір файлу (байт)"
            ),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="layers",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Шари"
            ),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="length_of_cuts",
            field=models.FloatField(default=0, verbose_name="Довжина різів (м)"),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="original_filename",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=255,
                verbose_name="Оригінальна назва файлу",
            ),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="processing_types",
            field=models.ManyToManyField(
                related_name="drawings",
                to="core.processingtype",
                verbose_name="Типи обробки",
            ),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата завантаження"
            ),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drawings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Користувач",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="available",
            field=models.BooleanField(default=True, verbose_name="Доступний"),
        ),
        migrations.AlterField(
            model_name="material",
            name="density",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Густина (кг/м³)"
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="material_name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Назва матеріалу"
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="material_type",
            field=models.CharField(
                choices=[
                    ("metal", "Метал"),
                    ("plastic", "Пластик"),
                    ("composites", "Композити"),
                ],
                default="metal",
                max_length=20,
                verbose_name="Тип матеріалу",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="price_per_kg",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Ціна за кг"
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="properties",
            field=models.TextField(blank=True, null=True, verbose_name="Властивості"),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Дата створення"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Примітки"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                default=core.models.generate_order_number,
                max_length=50,
                unique=True,
                verbose_name="Номер замовлення",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Чернетка"),
                    ("pending", "Очікує обробки"),
                    ("processing", "Обробляється"),
                    ("completed", "Завершено"),
                    ("cancelled", "Скасовано"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Загальна вартість",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата оновлення"),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Користувач",
            ),
        ),
        migrations.AlterField(
            model_name="processingtype",
            name="base_cost_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                verbose_name="Базова вартість за одиницю",
            ),
        ),
        migrations.AlterField(
            model_name="processingtype",
            name="cost_unit",
            field=models.CharField(
                max_length=50, verbose_name="Одиниця виміру вартості"
            ),
        ),
        migrations.AlterField(
            model_name="processingtype",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="processingtype",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активний"),
        ),
        migrations.AlterField(
            model_name="processingtype",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="processingtype",
            name="unit_name",
            field=models.CharField(max_length=255, verbose_name="Назва одиниці"),
        ),
    ]
