# Generated by Django 5.2.2 on 2025-07-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_consumables_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drawing",
            name="angles",
        ),
        migrations.RemoveField(
            model_name="drawing",
            name="bending_layers",
        ),
        migrations.RemoveField(
            model_name="drawing",
            name="cutting_layers",
        ),
        migrations.AddField(
            model_name="drawing",
            name="process_settings",
            field=models.JSONField(
                blank=True,
                default=list,
                null=True,
                verbose_name="Налаштування процесів",
            ),
        ),
    ]
