# Generated by Django 5.2.2 on 2025-07-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_remove_drawing_angles_remove_drawing_bending_layers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drawing",
            name="length_of_cuts",
        ),
    ]
