# Generated by Django 5.2.2 on 2025-07-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_drawing_length_of_cuts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drawing",
            name="process_settings",
        ),
        migrations.AddField(
            model_name="drawing",
            name="angles",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Кути"
            ),
        ),
        migrations.AddField(
            model_name="drawing",
            name="bending_layers",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Шари згинання"
            ),
        ),
        migrations.AddField(
            model_name="drawing",
            name="cutting_layers",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Шари різання"
            ),
        ),
        migrations.AddField(
            model_name="drawing",
            name="length_of_cuts",
            field=models.FloatField(default=0, verbose_name="Довжина різів (м)"),
        ),
    ]
