# Generated by Django 5.2.2 on 2025-07-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_remove_drawing_process_settings_drawing_angles_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drawing",
            name="angles",
        ),
        migrations.RemoveField(
            model_name="drawing",
            name="bending_layers",
        ),
        migrations.RemoveField(
            model_name="drawing",
            name="cutting_layers",
        ),
        migrations.RemoveField(
            model_name="drawing",
            name="length_of_cuts",
        ),
        migrations.RemoveField(
            model_name="drawing",
            name="processing_types",
        ),
        migrations.AddField(
            model_name="drawing",
            name="process_settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                null=True,
                verbose_name="Налаштування процесів",
            ),
        ),
    ]
